#ifndef ETCS_HASHES_H__
#define ETCS_HASHES_H__

// flags for make with -DETCS_PRODUCTION_BUILD loader side (see ETCS_API.h for module side)
#ifdef ETCS_PRODUCTION_BUILD
    #define ETCS_LOG_TO_FILE
    #undef  ETCS_REPL_SHELL
    // #undef  ETCS_VERBOSE_DISPATCH
#endif

// these two don't have include guards generated by default, use this proxy
#include "core_defs.h"
#include "ontology.h"

// ShellREPL.h is gone. Its two halves went to the places that already owned
// them: the navigator and the process entry points
// (shell_startup/drive_main_loop_then_exit) to core/CommandExecutor.h, which
// arrives transitively through core_defs.h above; the terminal to
// modules/ShellProvider, which is an ordinary provider loaded at runtime.
//
// So a loader build needs no extra include here, and -DETCS_REPL_SHELL no
// longer decides what compiles -- only what the loader DOES with it.
// trust layer, can add more hashes later
#include "core_hashes.h"
#include "ontology_hashes.h"
#include "libs_hashes.h"

#endif
