#ifndef ETCS_HASHES_H__
#define ETCS_HASHES_H__

// flags for make with -DETCS_PRODUCTION_BUILD loader side (see ETCS_API.h for module side)
#ifdef ETCS_PRODUCTION_BUILD
    #define ETCS_LOG_TO_FILE
    #undef  ETCS_REPL_SHELL
    // #undef  ETCS_VERBOSE_DISPATCH
#endif

// these two don't have include guards generated by default, use this proxy
#include "core_defs.h"
#include "ontology.h"

// Always included in a loader build now, regardless of ETCS_REPL_SHELL --
// ShellREPL.h provides both the interactive implementation (under its own
// ETCS_REPL_SHELL guard) and the drain-mode entry points
// (shell_startup/drive_main_loop_then_exit), so etcs.cc no longer needs
// to know the flag exists at all. Still gated on ETCS_LOADER -- module
// builds never touch this file.
#ifdef ETCS_LOADER
#include "ShellREPL.h"
#endif
// trust layer, can add more hashes later
#include "core_hashes.h"
#include "ontology_hashes.h"
#include "libs_hashes.h"

#endif
