#ifndef AIRTYMACROS_GENERATED_H__
#define AIRTYMACROS_GENERATED_H__
// --- Macro Expansion Helpers (arity 64) ---
#define FE_1(m, x)  m(x)
#define FE_2(m, x, ...)  m(x) FE_1(m, __VA_ARGS__)
#define FE_3(m, x, ...)  m(x) FE_2(m, __VA_ARGS__)
#define FE_4(m, x, ...)  m(x) FE_3(m, __VA_ARGS__)
#define FE_5(m, x, ...)  m(x) FE_4(m, __VA_ARGS__)
#define FE_6(m, x, ...)  m(x) FE_5(m, __VA_ARGS__)
#define FE_7(m, x, ...)  m(x) FE_6(m, __VA_ARGS__)
#define FE_8(m, x, ...)  m(x) FE_7(m, __VA_ARGS__)
#define FE_9(m, x, ...)  m(x) FE_8(m, __VA_ARGS__)
#define FE_10(m, x, ...)  m(x) FE_9(m, __VA_ARGS__)
#define FE_11(m, x, ...)  m(x) FE_10(m, __VA_ARGS__)
#define FE_12(m, x, ...)  m(x) FE_11(m, __VA_ARGS__)
#define FE_13(m, x, ...)  m(x) FE_12(m, __VA_ARGS__)
#define FE_14(m, x, ...)  m(x) FE_13(m, __VA_ARGS__)
#define FE_15(m, x, ...)  m(x) FE_14(m, __VA_ARGS__)
#define FE_16(m, x, ...)  m(x) FE_15(m, __VA_ARGS__)
#define FE_17(m, x, ...)  m(x) FE_16(m, __VA_ARGS__)
#define FE_18(m, x, ...)  m(x) FE_17(m, __VA_ARGS__)
#define FE_19(m, x, ...)  m(x) FE_18(m, __VA_ARGS__)
#define FE_20(m, x, ...)  m(x) FE_19(m, __VA_ARGS__)
#define FE_21(m, x, ...)  m(x) FE_20(m, __VA_ARGS__)
#define FE_22(m, x, ...)  m(x) FE_21(m, __VA_ARGS__)
#define FE_23(m, x, ...)  m(x) FE_22(m, __VA_ARGS__)
#define FE_24(m, x, ...)  m(x) FE_23(m, __VA_ARGS__)
#define FE_25(m, x, ...)  m(x) FE_24(m, __VA_ARGS__)
#define FE_26(m, x, ...)  m(x) FE_25(m, __VA_ARGS__)
#define FE_27(m, x, ...)  m(x) FE_26(m, __VA_ARGS__)
#define FE_28(m, x, ...)  m(x) FE_27(m, __VA_ARGS__)
#define FE_29(m, x, ...)  m(x) FE_28(m, __VA_ARGS__)
#define FE_30(m, x, ...)  m(x) FE_29(m, __VA_ARGS__)
#define FE_31(m, x, ...)  m(x) FE_30(m, __VA_ARGS__)
#define FE_32(m, x, ...)  m(x) FE_31(m, __VA_ARGS__)
#define FE_33(m, x, ...)  m(x) FE_32(m, __VA_ARGS__)
#define FE_34(m, x, ...)  m(x) FE_33(m, __VA_ARGS__)
#define FE_35(m, x, ...)  m(x) FE_34(m, __VA_ARGS__)
#define FE_36(m, x, ...)  m(x) FE_35(m, __VA_ARGS__)
#define FE_37(m, x, ...)  m(x) FE_36(m, __VA_ARGS__)
#define FE_38(m, x, ...)  m(x) FE_37(m, __VA_ARGS__)
#define FE_39(m, x, ...)  m(x) FE_38(m, __VA_ARGS__)
#define FE_40(m, x, ...)  m(x) FE_39(m, __VA_ARGS__)
#define FE_41(m, x, ...)  m(x) FE_40(m, __VA_ARGS__)
#define FE_42(m, x, ...)  m(x) FE_41(m, __VA_ARGS__)
#define FE_43(m, x, ...)  m(x) FE_42(m, __VA_ARGS__)
#define FE_44(m, x, ...)  m(x) FE_43(m, __VA_ARGS__)
#define FE_45(m, x, ...)  m(x) FE_44(m, __VA_ARGS__)
#define FE_46(m, x, ...)  m(x) FE_45(m, __VA_ARGS__)
#define FE_47(m, x, ...)  m(x) FE_46(m, __VA_ARGS__)
#define FE_48(m, x, ...)  m(x) FE_47(m, __VA_ARGS__)
#define FE_49(m, x, ...)  m(x) FE_48(m, __VA_ARGS__)
#define FE_50(m, x, ...)  m(x) FE_49(m, __VA_ARGS__)
#define FE_51(m, x, ...)  m(x) FE_50(m, __VA_ARGS__)
#define FE_52(m, x, ...)  m(x) FE_51(m, __VA_ARGS__)
#define FE_53(m, x, ...)  m(x) FE_52(m, __VA_ARGS__)
#define FE_54(m, x, ...)  m(x) FE_53(m, __VA_ARGS__)
#define FE_55(m, x, ...)  m(x) FE_54(m, __VA_ARGS__)
#define FE_56(m, x, ...)  m(x) FE_55(m, __VA_ARGS__)
#define FE_57(m, x, ...)  m(x) FE_56(m, __VA_ARGS__)
#define FE_58(m, x, ...)  m(x) FE_57(m, __VA_ARGS__)
#define FE_59(m, x, ...)  m(x) FE_58(m, __VA_ARGS__)
#define FE_60(m, x, ...)  m(x) FE_59(m, __VA_ARGS__)
#define FE_61(m, x, ...)  m(x) FE_60(m, __VA_ARGS__)
#define FE_62(m, x, ...)  m(x) FE_61(m, __VA_ARGS__)
#define FE_63(m, x, ...)  m(x) FE_62(m, __VA_ARGS__)
#define FE_64(m, x, ...)  m(x) FE_63(m, __VA_ARGS__)
#define BRACKET_UNWRAP(...) __VA_ARGS__
#define GET_MACRO(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,NAME,...) NAME
#define FOR_EACH(action,...) \
  GET_MACRO(__VA_ARGS__,FE_64,FE_63,FE_62,FE_61,FE_60,FE_59,FE_58,FE_57,FE_56,FE_55,FE_54,FE_53,FE_52,FE_51,FE_50,FE_49,FE_48,FE_47,FE_46,FE_45,FE_44,FE_43,FE_42,FE_41,FE_40,FE_39,FE_38,FE_37,FE_36,FE_35,FE_34,FE_33,FE_32,FE_31,FE_30,FE_29,FE_28,FE_27,FE_26,FE_25,FE_24,FE_23,FE_22,FE_21,FE_20,FE_19,FE_18,FE_17,FE_16,FE_15,FE_14,FE_13,FE_12,FE_11,FE_10,FE_9,FE_8,FE_7,FE_6,FE_5,FE_4,FE_3,FE_2,FE_1)(action,__VA_ARGS__)
// --- Fixed-Argument Expansion Helpers (arity 64) ---
#define FE_FIXED_1(m, f, x)  m(f, x)
#define FE_FIXED_2(m, f, x, ...)  m(f, x) FE_FIXED_1(m, f, __VA_ARGS__)
#define FE_FIXED_3(m, f, x, ...)  m(f, x) FE_FIXED_2(m, f, __VA_ARGS__)
#define FE_FIXED_4(m, f, x, ...)  m(f, x) FE_FIXED_3(m, f, __VA_ARGS__)
#define FE_FIXED_5(m, f, x, ...)  m(f, x) FE_FIXED_4(m, f, __VA_ARGS__)
#define FE_FIXED_6(m, f, x, ...)  m(f, x) FE_FIXED_5(m, f, __VA_ARGS__)
#define FE_FIXED_7(m, f, x, ...)  m(f, x) FE_FIXED_6(m, f, __VA_ARGS__)
#define FE_FIXED_8(m, f, x, ...)  m(f, x) FE_FIXED_7(m, f, __VA_ARGS__)
#define FE_FIXED_9(m, f, x, ...)  m(f, x) FE_FIXED_8(m, f, __VA_ARGS__)
#define FE_FIXED_10(m, f, x, ...)  m(f, x) FE_FIXED_9(m, f, __VA_ARGS__)
#define FE_FIXED_11(m, f, x, ...)  m(f, x) FE_FIXED_10(m, f, __VA_ARGS__)
#define FE_FIXED_12(m, f, x, ...)  m(f, x) FE_FIXED_11(m, f, __VA_ARGS__)
#define FE_FIXED_13(m, f, x, ...)  m(f, x) FE_FIXED_12(m, f, __VA_ARGS__)
#define FE_FIXED_14(m, f, x, ...)  m(f, x) FE_FIXED_13(m, f, __VA_ARGS__)
#define FE_FIXED_15(m, f, x, ...)  m(f, x) FE_FIXED_14(m, f, __VA_ARGS__)
#define FE_FIXED_16(m, f, x, ...)  m(f, x) FE_FIXED_15(m, f, __VA_ARGS__)
#define FE_FIXED_17(m, f, x, ...)  m(f, x) FE_FIXED_16(m, f, __VA_ARGS__)
#define FE_FIXED_18(m, f, x, ...)  m(f, x) FE_FIXED_17(m, f, __VA_ARGS__)
#define FE_FIXED_19(m, f, x, ...)  m(f, x) FE_FIXED_18(m, f, __VA_ARGS__)
#define FE_FIXED_20(m, f, x, ...)  m(f, x) FE_FIXED_19(m, f, __VA_ARGS__)
#define FE_FIXED_21(m, f, x, ...)  m(f, x) FE_FIXED_20(m, f, __VA_ARGS__)
#define FE_FIXED_22(m, f, x, ...)  m(f, x) FE_FIXED_21(m, f, __VA_ARGS__)
#define FE_FIXED_23(m, f, x, ...)  m(f, x) FE_FIXED_22(m, f, __VA_ARGS__)
#define FE_FIXED_24(m, f, x, ...)  m(f, x) FE_FIXED_23(m, f, __VA_ARGS__)
#define FE_FIXED_25(m, f, x, ...)  m(f, x) FE_FIXED_24(m, f, __VA_ARGS__)
#define FE_FIXED_26(m, f, x, ...)  m(f, x) FE_FIXED_25(m, f, __VA_ARGS__)
#define FE_FIXED_27(m, f, x, ...)  m(f, x) FE_FIXED_26(m, f, __VA_ARGS__)
#define FE_FIXED_28(m, f, x, ...)  m(f, x) FE_FIXED_27(m, f, __VA_ARGS__)
#define FE_FIXED_29(m, f, x, ...)  m(f, x) FE_FIXED_28(m, f, __VA_ARGS__)
#define FE_FIXED_30(m, f, x, ...)  m(f, x) FE_FIXED_29(m, f, __VA_ARGS__)
#define FE_FIXED_31(m, f, x, ...)  m(f, x) FE_FIXED_30(m, f, __VA_ARGS__)
#define FE_FIXED_32(m, f, x, ...)  m(f, x) FE_FIXED_31(m, f, __VA_ARGS__)
#define FE_FIXED_33(m, f, x, ...)  m(f, x) FE_FIXED_32(m, f, __VA_ARGS__)
#define FE_FIXED_34(m, f, x, ...)  m(f, x) FE_FIXED_33(m, f, __VA_ARGS__)
#define FE_FIXED_35(m, f, x, ...)  m(f, x) FE_FIXED_34(m, f, __VA_ARGS__)
#define FE_FIXED_36(m, f, x, ...)  m(f, x) FE_FIXED_35(m, f, __VA_ARGS__)
#define FE_FIXED_37(m, f, x, ...)  m(f, x) FE_FIXED_36(m, f, __VA_ARGS__)
#define FE_FIXED_38(m, f, x, ...)  m(f, x) FE_FIXED_37(m, f, __VA_ARGS__)
#define FE_FIXED_39(m, f, x, ...)  m(f, x) FE_FIXED_38(m, f, __VA_ARGS__)
#define FE_FIXED_40(m, f, x, ...)  m(f, x) FE_FIXED_39(m, f, __VA_ARGS__)
#define FE_FIXED_41(m, f, x, ...)  m(f, x) FE_FIXED_40(m, f, __VA_ARGS__)
#define FE_FIXED_42(m, f, x, ...)  m(f, x) FE_FIXED_41(m, f, __VA_ARGS__)
#define FE_FIXED_43(m, f, x, ...)  m(f, x) FE_FIXED_42(m, f, __VA_ARGS__)
#define FE_FIXED_44(m, f, x, ...)  m(f, x) FE_FIXED_43(m, f, __VA_ARGS__)
#define FE_FIXED_45(m, f, x, ...)  m(f, x) FE_FIXED_44(m, f, __VA_ARGS__)
#define FE_FIXED_46(m, f, x, ...)  m(f, x) FE_FIXED_45(m, f, __VA_ARGS__)
#define FE_FIXED_47(m, f, x, ...)  m(f, x) FE_FIXED_46(m, f, __VA_ARGS__)
#define FE_FIXED_48(m, f, x, ...)  m(f, x) FE_FIXED_47(m, f, __VA_ARGS__)
#define FE_FIXED_49(m, f, x, ...)  m(f, x) FE_FIXED_48(m, f, __VA_ARGS__)
#define FE_FIXED_50(m, f, x, ...)  m(f, x) FE_FIXED_49(m, f, __VA_ARGS__)
#define FE_FIXED_51(m, f, x, ...)  m(f, x) FE_FIXED_50(m, f, __VA_ARGS__)
#define FE_FIXED_52(m, f, x, ...)  m(f, x) FE_FIXED_51(m, f, __VA_ARGS__)
#define FE_FIXED_53(m, f, x, ...)  m(f, x) FE_FIXED_52(m, f, __VA_ARGS__)
#define FE_FIXED_54(m, f, x, ...)  m(f, x) FE_FIXED_53(m, f, __VA_ARGS__)
#define FE_FIXED_55(m, f, x, ...)  m(f, x) FE_FIXED_54(m, f, __VA_ARGS__)
#define FE_FIXED_56(m, f, x, ...)  m(f, x) FE_FIXED_55(m, f, __VA_ARGS__)
#define FE_FIXED_57(m, f, x, ...)  m(f, x) FE_FIXED_56(m, f, __VA_ARGS__)
#define FE_FIXED_58(m, f, x, ...)  m(f, x) FE_FIXED_57(m, f, __VA_ARGS__)
#define FE_FIXED_59(m, f, x, ...)  m(f, x) FE_FIXED_58(m, f, __VA_ARGS__)
#define FE_FIXED_60(m, f, x, ...)  m(f, x) FE_FIXED_59(m, f, __VA_ARGS__)
#define FE_FIXED_61(m, f, x, ...)  m(f, x) FE_FIXED_60(m, f, __VA_ARGS__)
#define FE_FIXED_62(m, f, x, ...)  m(f, x) FE_FIXED_61(m, f, __VA_ARGS__)
#define FE_FIXED_63(m, f, x, ...)  m(f, x) FE_FIXED_62(m, f, __VA_ARGS__)
#define FE_FIXED_64(m, f, x, ...)  m(f, x) FE_FIXED_63(m, f, __VA_ARGS__)
#define GET_MACRO_FIXED(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,NAME,...) NAME
#define FOR_EACH_FIXED(action, fixed, ...) \
  GET_MACRO_FIXED(__VA_ARGS__,FE_FIXED_64,FE_FIXED_63,FE_FIXED_62,FE_FIXED_61,FE_FIXED_60,FE_FIXED_59,FE_FIXED_58,FE_FIXED_57,FE_FIXED_56,FE_FIXED_55,FE_FIXED_54,FE_FIXED_53,FE_FIXED_52,FE_FIXED_51,FE_FIXED_50,FE_FIXED_49,FE_FIXED_48,FE_FIXED_47,FE_FIXED_46,FE_FIXED_45,FE_FIXED_44,FE_FIXED_43,FE_FIXED_42,FE_FIXED_41,FE_FIXED_40,FE_FIXED_39,FE_FIXED_38,FE_FIXED_37,FE_FIXED_36,FE_FIXED_35,FE_FIXED_34,FE_FIXED_33,FE_FIXED_32,FE_FIXED_31,FE_FIXED_30,FE_FIXED_29,FE_FIXED_28,FE_FIXED_27,FE_FIXED_26,FE_FIXED_25,FE_FIXED_24,FE_FIXED_23,FE_FIXED_22,FE_FIXED_21,FE_FIXED_20,FE_FIXED_19,FE_FIXED_18,FE_FIXED_17,FE_FIXED_16,FE_FIXED_15,FE_FIXED_14,FE_FIXED_13,FE_FIXED_12,FE_FIXED_11,FE_FIXED_10,FE_FIXED_9,FE_FIXED_8,FE_FIXED_7,FE_FIXED_6,FE_FIXED_5,FE_FIXED_4,FE_FIXED_3,FE_FIXED_2,FE_FIXED_1)(action, fixed, __VA_ARGS__)
// --- Comma-joining variant (arity 64) ---
#define FE_C_1(m, x)  m(x)
#define FE_C_2(m, x, ...)  m(x), FE_C_1(m, __VA_ARGS__)
#define FE_C_3(m, x, ...)  m(x), FE_C_2(m, __VA_ARGS__)
#define FE_C_4(m, x, ...)  m(x), FE_C_3(m, __VA_ARGS__)
#define FE_C_5(m, x, ...)  m(x), FE_C_4(m, __VA_ARGS__)
#define FE_C_6(m, x, ...)  m(x), FE_C_5(m, __VA_ARGS__)
#define FE_C_7(m, x, ...)  m(x), FE_C_6(m, __VA_ARGS__)
#define FE_C_8(m, x, ...)  m(x), FE_C_7(m, __VA_ARGS__)
#define FE_C_9(m, x, ...)  m(x), FE_C_8(m, __VA_ARGS__)
#define FE_C_10(m, x, ...)  m(x), FE_C_9(m, __VA_ARGS__)
#define FE_C_11(m, x, ...)  m(x), FE_C_10(m, __VA_ARGS__)
#define FE_C_12(m, x, ...)  m(x), FE_C_11(m, __VA_ARGS__)
#define FE_C_13(m, x, ...)  m(x), FE_C_12(m, __VA_ARGS__)
#define FE_C_14(m, x, ...)  m(x), FE_C_13(m, __VA_ARGS__)
#define FE_C_15(m, x, ...)  m(x), FE_C_14(m, __VA_ARGS__)
#define FE_C_16(m, x, ...)  m(x), FE_C_15(m, __VA_ARGS__)
#define FE_C_17(m, x, ...)  m(x), FE_C_16(m, __VA_ARGS__)
#define FE_C_18(m, x, ...)  m(x), FE_C_17(m, __VA_ARGS__)
#define FE_C_19(m, x, ...)  m(x), FE_C_18(m, __VA_ARGS__)
#define FE_C_20(m, x, ...)  m(x), FE_C_19(m, __VA_ARGS__)
#define FE_C_21(m, x, ...)  m(x), FE_C_20(m, __VA_ARGS__)
#define FE_C_22(m, x, ...)  m(x), FE_C_21(m, __VA_ARGS__)
#define FE_C_23(m, x, ...)  m(x), FE_C_22(m, __VA_ARGS__)
#define FE_C_24(m, x, ...)  m(x), FE_C_23(m, __VA_ARGS__)
#define FE_C_25(m, x, ...)  m(x), FE_C_24(m, __VA_ARGS__)
#define FE_C_26(m, x, ...)  m(x), FE_C_25(m, __VA_ARGS__)
#define FE_C_27(m, x, ...)  m(x), FE_C_26(m, __VA_ARGS__)
#define FE_C_28(m, x, ...)  m(x), FE_C_27(m, __VA_ARGS__)
#define FE_C_29(m, x, ...)  m(x), FE_C_28(m, __VA_ARGS__)
#define FE_C_30(m, x, ...)  m(x), FE_C_29(m, __VA_ARGS__)
#define FE_C_31(m, x, ...)  m(x), FE_C_30(m, __VA_ARGS__)
#define FE_C_32(m, x, ...)  m(x), FE_C_31(m, __VA_ARGS__)
#define FE_C_33(m, x, ...)  m(x), FE_C_32(m, __VA_ARGS__)
#define FE_C_34(m, x, ...)  m(x), FE_C_33(m, __VA_ARGS__)
#define FE_C_35(m, x, ...)  m(x), FE_C_34(m, __VA_ARGS__)
#define FE_C_36(m, x, ...)  m(x), FE_C_35(m, __VA_ARGS__)
#define FE_C_37(m, x, ...)  m(x), FE_C_36(m, __VA_ARGS__)
#define FE_C_38(m, x, ...)  m(x), FE_C_37(m, __VA_ARGS__)
#define FE_C_39(m, x, ...)  m(x), FE_C_38(m, __VA_ARGS__)
#define FE_C_40(m, x, ...)  m(x), FE_C_39(m, __VA_ARGS__)
#define FE_C_41(m, x, ...)  m(x), FE_C_40(m, __VA_ARGS__)
#define FE_C_42(m, x, ...)  m(x), FE_C_41(m, __VA_ARGS__)
#define FE_C_43(m, x, ...)  m(x), FE_C_42(m, __VA_ARGS__)
#define FE_C_44(m, x, ...)  m(x), FE_C_43(m, __VA_ARGS__)
#define FE_C_45(m, x, ...)  m(x), FE_C_44(m, __VA_ARGS__)
#define FE_C_46(m, x, ...)  m(x), FE_C_45(m, __VA_ARGS__)
#define FE_C_47(m, x, ...)  m(x), FE_C_46(m, __VA_ARGS__)
#define FE_C_48(m, x, ...)  m(x), FE_C_47(m, __VA_ARGS__)
#define FE_C_49(m, x, ...)  m(x), FE_C_48(m, __VA_ARGS__)
#define FE_C_50(m, x, ...)  m(x), FE_C_49(m, __VA_ARGS__)
#define FE_C_51(m, x, ...)  m(x), FE_C_50(m, __VA_ARGS__)
#define FE_C_52(m, x, ...)  m(x), FE_C_51(m, __VA_ARGS__)
#define FE_C_53(m, x, ...)  m(x), FE_C_52(m, __VA_ARGS__)
#define FE_C_54(m, x, ...)  m(x), FE_C_53(m, __VA_ARGS__)
#define FE_C_55(m, x, ...)  m(x), FE_C_54(m, __VA_ARGS__)
#define FE_C_56(m, x, ...)  m(x), FE_C_55(m, __VA_ARGS__)
#define FE_C_57(m, x, ...)  m(x), FE_C_56(m, __VA_ARGS__)
#define FE_C_58(m, x, ...)  m(x), FE_C_57(m, __VA_ARGS__)
#define FE_C_59(m, x, ...)  m(x), FE_C_58(m, __VA_ARGS__)
#define FE_C_60(m, x, ...)  m(x), FE_C_59(m, __VA_ARGS__)
#define FE_C_61(m, x, ...)  m(x), FE_C_60(m, __VA_ARGS__)
#define FE_C_62(m, x, ...)  m(x), FE_C_61(m, __VA_ARGS__)
#define FE_C_63(m, x, ...)  m(x), FE_C_62(m, __VA_ARGS__)
#define FE_C_64(m, x, ...)  m(x), FE_C_63(m, __VA_ARGS__)
#define GET_MACRO_C(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,NAME,...) NAME
#define FOR_EACH_COMMA(action,...) \
  GET_MACRO_C(__VA_ARGS__,FE_C_64,FE_C_63,FE_C_62,FE_C_61,FE_C_60,FE_C_59,FE_C_58,FE_C_57,FE_C_56,FE_C_55,FE_C_54,FE_C_53,FE_C_52,FE_C_51,FE_C_50,FE_C_49,FE_C_48,FE_C_47,FE_C_46,FE_C_45,FE_C_44,FE_C_43,FE_C_42,FE_C_41,FE_C_40,FE_C_39,FE_C_38,FE_C_37,FE_C_36,FE_C_35,FE_C_34,FE_C_33,FE_C_32,FE_C_31,FE_C_30,FE_C_29,FE_C_28,FE_C_27,FE_C_26,FE_C_25,FE_C_24,FE_C_23,FE_C_22,FE_C_21,FE_C_20,FE_C_19,FE_C_18,FE_C_17,FE_C_16,FE_C_15,FE_C_14,FE_C_13,FE_C_12,FE_C_11,FE_C_10,FE_C_9,FE_C_8,FE_C_7,FE_C_6,FE_C_5,FE_C_4,FE_C_3,FE_C_2,FE_C_1)(action,__VA_ARGS__)
// --- ETCS_DISPATCH_SELECT (arity 64) ---
// Self-contained concat helper -- identical in body to ETCS_API.h's own
// ETCS_DISPATCH_CONCAT2/_ (redefining with an IDENTICAL token sequence is
// not an error), so this block doesn't depend on include order elsewhere.
#define ETCS_DISPATCH_CONCAT2_(a,b)   a##b
#define ETCS_DISPATCH_CONCAT2(a,b)    ETCS_DISPATCH_CONCAT2_(a,b)
#define ETCS_DISPATCH_ARG16_(_0,_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,N,...) N
#define ETCS_DISPATCH_HAS_COMMA(...) ETCS_DISPATCH_ARG16_(__VA_ARGS__,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0)
#define ETCS_DISPATCH_TRIGGER_PAREN_(...) ,
#define ETCS_DISPATCH_PASTE5_(a,b,c,d,e) a##b##c##d##e
#define ETCS_DISPATCH_PASTE5(a,b,c,d,e) ETCS_DISPATCH_PASTE5_(a,b,c,d,e)
#define ETCS_DISPATCH_IS_EMPTY_CASE_0001 ,
#define ETCS_DISPATCH_ISEMPTY_(_0,_1,_2,_3) \
    ETCS_DISPATCH_HAS_COMMA(ETCS_DISPATCH_PASTE5(ETCS_DISPATCH_IS_EMPTY_CASE_, _0, _1, _2, _3))
#define ETCS_DISPATCH_ISEMPTY(...) \
    ETCS_DISPATCH_ISEMPTY_( \
        ETCS_DISPATCH_HAS_COMMA(__VA_ARGS__), \
        ETCS_DISPATCH_HAS_COMMA(ETCS_DISPATCH_TRIGGER_PAREN_ __VA_ARGS__), \
        ETCS_DISPATCH_HAS_COMMA(__VA_ARGS__ (~)), \
        ETCS_DISPATCH_HAS_COMMA(ETCS_DISPATCH_TRIGGER_PAREN_ __VA_ARGS__ (~)) \
    )
#define ETCS_DISPATCH_SELECT_IF_0(t, f) f
#define ETCS_DISPATCH_SELECT_IF_1(t, f) t
#define ETCS_DISPATCH_SELECT_IF_(cond, t, f) ETCS_DISPATCH_CONCAT2(ETCS_DISPATCH_SELECT_IF_, cond)(t, f)
#define ETCS_DISPATCH_SELECT_IF(cond, t, f)  ETCS_DISPATCH_SELECT_IF_(cond, t, f)
#define ETCS_DISPATCH_SELECT(...) \
    ETCS_DISPATCH_SELECT_IF(ETCS_DISPATCH_ISEMPTY(__VA_ARGS__), 0, N)
#endif // AIRTYMACROS_GENERATED_H__
